// Verify parseAddress matches Go address.FromString
// Vectors generated by: go run ./cmd/address-test-vectors (in litedag-blockchain)
// Run: pnpm test (in apps/wallet)

import { readFileSync } from "fs"
import { parseAddress } from "../lib/address"

const vectors: { str: string; addr_hex: string; pid: number }[] = JSON.parse(
  readFileSync(new URL("../../../address-test-vectors.json", import.meta.url), "utf-8")
)

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
}

let passed = 0
let failed = 0

for (const v of vectors) {
  try {
    const result = parseAddress(v.str)
    const gotHex = toHex(result.addr)

    if (gotHex !== v.addr_hex) {
      console.error(`FAIL [${v.str}]: addr_hex\n  want: ${v.addr_hex}\n  got:  ${gotHex}`)
      failed++
      continue
    }
    if (result.paymentId !== v.pid) {
      console.error(`FAIL [${v.str}]: paymentId\n  want: ${v.pid}\n  got:  ${result.paymentId}`)
      failed++
      continue
    }
    passed++
  } catch (e: unknown) {
    console.error(`FAIL [${v.str}]: ${e instanceof Error ? e.message : e}`)
    failed++
  }
}

console.log(`\n${passed}/${vectors.length} vectors passed`)
if (failed > 0) {
  process.exit(1)
}
console.log("All vectors match Go address.FromString.")
